### ISSUE TITLE
Ajout d'un paramètre FILENAME

### ISSUE THREAD

**Issue by vsasyan-ignf** [rok4/server#34]
Il serait intéressant de permettre à l'utilisateur d'ajouter un paramètre `filename` dans la requête url afin de préciser un nom de fichier pour sauver la données renvoyée (utilisation de l'entête `Content-Disposition`).

## Spécifications

Pour toutes les requêtes effectuées (`GetCapabilities`, `GetMap`, ...), permettre d'ajouter le mot clef `FILENAME` :

* Propriété à ajouter : `FILENAME`
* Valeurs possibles : libre
* Vérification entre l’extension du nom de fichier et le `FORMAT` demandé : pas nécessaire, à voir si c'est facile ou non
* Résultat : `Content-Disposition: attachment; filename="$FILENAME"` ajouté dans le header de la réponse

## Cas d'usage

Générer un lien permettant à un utilisateur de récupérer un fichier correctement nommé.

Exemple :

* le lien suivant : https://data.geopf.fr/wms-r/wms?SERVICE=WMS&VERSION=1.3.0&EXCEPTIONS=text/xml&REQUEST=GetMap&LAYERS=ORTHOIMAGERY.ORTHOPHOTOS&FORMAT=image/tiff&STYLES=&CRS=EPSG:2154&BBOX=435000,6291000.006,436000,6292000&WIDTH=2000&HEIGHT=2000
* **Comportement actuel** : le navigateur affiche l'image (s'il gère le format) ou la télécharge en la nommant `image.tif`.
* lien complété avec `FILENAME` : https://data.geopf.fr/wms-r/wms?SERVICE=WMS&VERSION=1.3.0&EXCEPTIONS=text/xml&REQUEST=GetMap&LAYERS=ORTHOIMAGERY.ORTHOPHOTOS&FORMAT=image/tiff&STYLES=&CRS=EPSG:2154&BBOX=435000,6291000.006,436000,6292000&WIDTH=2000&HEIGHT=2000&FILENAME=BDORTHO_FXX_LAMB93_4350_6292.tif
* **Comportement cible** : le navigateur propose de sauvegarder l'image en la nommant `BDORTHO_FXX_LAMB93_4350_6292.tif`

 ## Source

Doc Mozilla sur le header : https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

C'est inspiré de : https://docs.geoserver.org/2.22.x/en/user/services/wms/vendor.html

Il pourrait être intéressant de voir si d'autre paramètres sont intéressants éventuellement.

**Comment by Dolite** [comment]
Pas besoin de contrôler l'extension du filename fourni : le navigateur (au moins firefox) la change si celle du filename ne correspond pas au content-type dans la réponse.
