### ISSUE TITLE
Sortir proprement lors d'un problème de socket

### ISSUE THREAD

**Issue by Dolite** [rok4/server#4]
Lorsque l'on essaye de démarrer le serveur sur un port déjà occupé, il sort en erreur sans logger la raison. Il faudrait ajouter un log fatal explicite

Développement : C++
Charge de développement : 0.5 jour
Charge de test : 0.5 jour

**Comment by lowzonenose** [comment]
Documentation développeur [FCGI v2.4.0](https://fossies.org/dox/fcgi-2.4.0/fcgiapp_8c.html#a8c3782550ffc987e11821aab7428aaef)

La méthode de la lib _FCGI_ utilisée dans _Rok4_ est [FCGX_OpenSocket](https://fossies.org/dox/fcgi-2.4.0/fcgiapp_8c.html#a8c3782550ffc987e11821aab7428aaef).

Et, cette dernière appelle [OS_CreateLocalIpcFd](https://fossies.org/dox/fcgi-2.4.0/os__unix_8c.html#a9efafbf1fa267aac4615052e066a1397).

Hors, cette méthode utilise l'instruction **exit()** sur une exception, et l'application sort brutalement sans pouvoir **catcher** l'erreur.

> bind/listen : address already in use
```
  359 if(bind(listenSock, (struct sockaddr *) &sa.unixVariant, servLen) < 0
  360        || listen(listenSock, backlog) < 0) {
  361         perror("bind/listen");
  362         exit(errno);
  363     }
```

**Comment by lowzonenose** [comment]
Difficile de gérer l'exception sans passer par une encapsulation du process Rok4 dans un shell, juste pour catcher des erreurs...
