### ISSUE TITLE
⏳ Implémenter l'API OGC Tiles (~WMTS)

### ISSUE THREAD

**Issue by Dolite** [rok4/server#6]
⏳  En attente de stabilisation des API

L'OGC est en train de spécifier des nouvelles API modernes, pour venir remplacer les anciennes. Concernant le serveur ROK4, on va venir compléter les interfaces gérées avec l'[API Tiles](https://ogcapi.ogc.org/tiles/) ([GitHub](https://github.com/opengeospatial/ogcapi-tiles))

Specs OpenAPI :

* [Redoc](https://opengeospatial.github.io/architecture-dwg/api-tiles/index.html)
* [SwaggerUI](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/opengeospatial/ogcapi-tiles/master/openapi/ogcapi-tiles-1.bundled.json)

Il faut partir sur les routes permettant la fourniture d'un style et le nom de la collection (couche).

Celle ci ressemble énormément au Tile Map Service

Développement : C++
Charge d'analyse : 1 semaine
Charge de développement : 1.5 semaine
Charge de test : 2 jours

Racine du service : /ogcapitiles

## GetCapabilities

- [x] /collections
  - [x] gestion du paramètre limit
  - [x] gestion du  paramètre bbox
  - [ ] gestion du  paramètre bbox-crs
- [x] /collections/**{id}**/tiles : (les données vecteur, avec forcément un seul tileset, celui correspondant au TMS natif)
- [x] /collections/**{id}**/map/tiles : (les données raster, avec un tile set par tms d'exposition) 

## Tile Matrix Sets

- [x] /tilematrixsets
- [x] /tilematrixsets/**{id}**

URI pour afficher les **tilematrixsetLimits**
- [ ] /tiles/**{tileMatrixSetId}**
- [ ] /map/tiles/**{tileMatrixSetId}** 

ou l'utilisation de la route coverage : 
- /collections/**{collectionId}**/coverage/map/tiles/**{tileMatrixSetId}**
-  /collections/**{collectionId}**/coverage/tiles/**{tileMatrixSetId}**

## GetTile raster

- [x] /styles/<id>/map/tiles/**{tms id}**/**{level}**/**{row}**/**{col}** : avec le paramètre collections obligatoire et de longueur 1
- [x] /map/tiles/**{tms id}**/**{level}**/**{row}**/**{col}** : avec le paramètre collections obligatoire et de longueur 1 et le style par défaut de la couche
- [x] /collections/**{id}**/styles/<id>/map/tiles/**{tms id}**/**{level}**/**{row}**/**{col}**
- [x] /collections/**{id}**/map/tiles/**{tms id}**/**{level}**/**{row}**/**{col}** : avec le style de la couche par défaut

## GetTile vector (sans subset ou reprojection)

- [x] /tiles/**{tms id}**/**{level}**/**{row}**/**{col}** : avec le paramètre collections obligatoire et de longueur 1, et tms id = celui natif de la pyramide
- [x] /collections/**{id}**/tiles/**{tms id}**/**{level}**/**{row}**/**{col}** : avec tms id = celui natif de la pyramide

**Comment by lowzonenose** [comment]
OGC API - Tiles - Part 1 v1.0.0 final release
https://github.com/opengeospatial/ogcapi-tiles/releases/tag/1.0.0
